name: Update Docs
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-docc:
    name: Build docs with DocC
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Select proper Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_16.1.app
      - name: Run DocC
        run: >
          swift package --allow-writing-to-directory docs generate-documentation
          --target Lanyard
          --disable-indexing
          --output-path docs
          --transform-for-static-hosting
          --hosting-base-path Lanyard
      - name: Upload generated docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy-docs:
    name: Deploy docs to Pages
    needs: [build-docc]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
